[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NETLIFY_USE_YARN = "false"
  SECRETS_SCAN_OMIT_PATHS = "/dist/assets/*"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.secrets]
  scan = false