[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NETLIFY_USE_YARN = "false"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Configure secret detection
[build.processing.secrets]
  # Exclude Firebase config values from secret scanning
  exclude = ["VITE_FIREBASE_*"]